name: dotdo
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: ">=2.3.0 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    animated_stack: ^0.1.0
    cloud_firestore: ^0.16.0+1
    cupertino_icons: ^1.0.0
    date_picker_timeline: ^1.2.1
    equatable: ^2.0.0
    firebase_auth: ^0.20.1
    firebase_core: ^0.7.0
    firebase_storage: ^7.0.0
    flutter_hooks: ^0.15.0
    flutter_iconpicker: ^2.2.3
    flutter_speed_dial: ^2.1.1
    flutter_svg: ^0.19.1
    font_awesome_flutter: ^8.11.0
    get_it: ^5.0.6
    google_fonts: ^1.1.2
    google_sign_in: ^4.5.9
    image_picker: ^0.6.7+22
    logger: ^0.9.2
    responsive_builder: ^0.3.0
    smooth_page_indicator: ^0.2.1
    stacked: ^1.9.5
    stacked_firebase_auth: ^0.1.0+1
    stacked_hooks: ^0.1.3+2
    stacked_services: ^0.7.2
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.8.1
    flutter_native_splash: ^0.3.2

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon.png"

flutter_native_splash:
    android: true
    ios: true
    color: "FFFFFF"
    image: "assets/LogoLight.png"
    color_dark: "1C1D22"
    image_dark: "assets/LogoDark.png"

flutter:
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/
    # - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
