name: dotdo
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: ">=2.3.0 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    animated_stack: ^0.2.0
    cloud_firestore: ^2.0.0
    connectivity: ^3.0.3
    cupertino_icons: ^1.0.3
    date_picker_timeline: ^1.2.3
    equatable: ^2.0.0
    firebase_auth: ^1.1.3
    firebase_core: ^1.1.0
    firebase_storage: ^8.0.5
    flutter_hooks: ^0.16.0
    flutter_iconpicker: ^3.0.0
    flutter_speed_dial: ^3.0.5
    flutter_svg: ^0.22.0
    font_awesome_flutter: ^9.0.0
    get_it: ^6.1.1
    google_fonts: ^2.0.0
    google_sign_in: ^5.0.2
    image_picker: ^0.7.4
    logger: ^1.0.0
    observable_ish: ^3.0.0
    responsive_builder: ^0.4.1
    smooth_page_indicator: ^0.3.0-nullsafety.0
    stacked: ^2.1.1
    stacked_firebase_auth: ^0.2.4
    stacked_hooks: ^0.2.0
    stacked_services: ^0.8.5
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.9.0
    flutter_native_splash: ^1.1.8+4

flutter_icons:
    android: true
    ios: true
    image_path: "assets/icon.png"

flutter_native_splash:
    android: true
    ios: true
    color: "FFFFFF"
    image: "assets/LogoLight.png"
    color_dark: "1C1D22"
    image_dark: "assets/LogoDark.png"

flutter:
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/
    # - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
