import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

const appBarShapeBorder = RoundedRectangleBorder(
  borderRadius: BorderRadius.only(
    bottomLeft: Radius.circular(20),
    bottomRight: Radius.circular(20),
  ),
);

const List<IconData> iconDataList = [
  FontAwesomeIcons.virus,
  FontAwesomeIcons.brain,
  FontAwesomeIcons.crosshairs,
  FontAwesomeIcons.tasks,
  FontAwesomeIcons.water,
  FontAwesomeIcons.book,
  FontAwesomeIcons.bookOpen,
  FontAwesomeIcons.bookDead,
  FontAwesomeIcons.bookmark,
  FontAwesomeIcons.leaf,
  FontAwesomeIcons.redo,
  FontAwesomeIcons.pen,
  FontAwesomeIcons.americanSignLanguageInterpreting,
  FontAwesomeIcons.baby,
  FontAwesomeIcons.dollarSign,
  FontAwesomeIcons.moneyBill,
  FontAwesomeIcons.laptop,
  FontAwesomeIcons.laptopCode,
  FontAwesomeIcons.phone,
  FontAwesomeIcons.handshake,
  FontAwesomeIcons.thumbsUp,
  FontAwesomeIcons.thumbsDown,
  FontAwesomeIcons.babyCarriage,
  FontAwesomeIcons.bomb,
  FontAwesomeIcons.lock,
  FontAwesomeIcons.hamburger,
  FontAwesomeIcons.fish,
  FontAwesomeIcons.iceCream,
  FontAwesomeIcons.appleAlt,
  FontAwesomeIcons.angry,
  FontAwesomeIcons.grinBeam,
  FontAwesomeIcons.arrowsAlt,
  FontAwesomeIcons.bolt,
  FontAwesomeIcons.bone,
  FontAwesomeIcons.airFreshener,
  FontAwesomeIcons.walking,
  FontAwesomeIcons.dumbbell,
  FontAwesomeIcons.bicycle,
  FontAwesomeIcons.bus,
  FontAwesomeIcons.car,
  FontAwesomeIcons.plane,
  FontAwesomeIcons.cat,
  FontAwesomeIcons.robot,
  FontAwesomeIcons.skull,
  FontAwesomeIcons.tshirt,
  FontAwesomeIcons.cloud,
  FontAwesomeIcons.coffee,
  FontAwesomeIcons.cookieBite,
  FontAwesomeIcons.creditCard,
  FontAwesomeIcons.heart,
  FontAwesomeIcons.mapMarkedAlt,
  FontAwesomeIcons.radiation,
  FontAwesomeIcons.footballBall,
  FontAwesomeIcons.basketballBall,
  FontAwesomeIcons.batteryFull,
  FontAwesomeIcons.bong,
  FontAwesomeIcons.boxOpen,
  FontAwesomeIcons.broom,
  FontAwesomeIcons.glassWhiskey,
  FontAwesomeIcons.wineGlassAlt
];
